language: rust
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libegl1-mesa-dev libgles2-mesa-dev
script:
        - cargo build --verbose --workspace
        - cargo test --verbose --workspace

# safelist
branches:
      only:
         - main
