language: rust
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y  libsdl2-dev
script:
        - cargo build --verbose --workspace
        - cargo test --verbose --workspace

