[package]
name = "boostvoronoi"
version = "0.4.1"
authors = ["eadf"]
edition = "2018"
description = "Boost voronoi ported to 100% rust"
readme = "README.md"
repository = "https://github.com/eadf/boostvoronoi.rs"
license = "BSL-1.0"
keywords = ["voronoi", "sweepline", "geometry"]

[dependencies]
num = "^0.3.1"
ordered-float = "^2.1.1"
fnv = "^1.0.7"
rb_tree = "^0.3.4"
#rb_tree = "^0.3.5"
#rb_tree = {path = "/Users/eadf/Develop/external/rb_tree"}

vec_map = "^0.8.2"
num-bigint = "^0.3.1"
num-traits = "^0.2.14"
thiserror = "^1.0.24"

[features]
console_debug = []

[[example]]
name = "piston_gui"
path = "example/piston_gui.rs"

# this bin is for development test purposes
[[bin]]
name = "main"
path = "example/main.rs"
required-features = ["console_debug"]

[dev-dependencies]
piston = "^0.52.1"
piston2d-opengl_graphics = "^0.77.0"
piston2d-graphics = "^0.39.0"
piston2d-touch_visualizer = "^0.29.0"
pistoncore-sdl2_window = "^0.67.0"
geo = "^0.17.0"

