[package]
name = "boostvoronoi"
version = "0.4.2"
authors = ["eadf"]
edition = "2018"
description = "Boost voronoi ported to 100% rust"
readme = "README.md"
repository = "https://github.com/eadf/boostvoronoi.rs"
license = "BSL-1.0"
keywords = ["voronoi", "sweepline", "geometry"]

[dependencies]
num = ">=0.3.1,<0.5.0"
ordered-float = "^2.1.1"
fnv = "^1.0.7"
rb_tree = "^0.3.5"
vec_map = "^0.8.2"
yabf = {version="^0.0.3",default-features=false}
num-traits = "^0.2.14"
thiserror = "^1.0.24"
bitflags = "^1.2.1"

[features]
console_debug = []

[[example]]
name = "fltk_gui"
path = "example/fltk_gui.rs"

# this bin is for development test purposes
[[bin]]
name = "main"
path = "example/main.rs"

[dev-dependencies]
geo = "^0.17.1"
fltk = "^0.15.6"


