[package]
name = "boostvoronoi"
version = "0.8.4"
authors = ["eadf"]
edition = "2018"
description = "Boost voronoi ported to 100% rust"
readme = "README.md"
repository = "https://github.com/eadf/boostvoronoi.rs"
license = "BSL-1.0"
keywords = ["voronoi", "sweepline", "geometry"]
exclude = [
    "img/*",
    "idea/*",
    ".github/*",
    "examples/input_data/*"
]

[dependencies]
num = ">=0.3.1,<0.5"
ordered-float = "2.5"
vec_map = "0.8"
yabf = {version="^0.1.1",default-features=false}
num-traits = "0.2"
thiserror = "1.0"
bitflags = "1.2"
libm = "0.2"
smallvec = "^1.6.1"
# using "geo" feature will enable From traits
geo = {version="0.18", optional=true}
# using "cgmath" feature will enable From traits
cgmath = {version="0.18", optional=true}
itertools = "0.10"
lazy_static = "1.4"

# These features are only for debug purposes, should normally not be used
[features]
console_debug = []
console_debug_eval = []
cpp_compat_debug = []
debug_always_exact = []
beachline_corruption_check = []

[[example]]
name = "fltk_gui"
path = "example/fltk_gui.rs"

# this example is for development test purposes
[[example]]
name = "main"
path = "example/main.rs"

[[example]]
name = "readme"
path = "example/readme.rs"

[build-dependencies]
version_check = "0.9"

[dev-dependencies]
geo = "=0.18"
fltk = "1.0"
criterion = "0.3"
approx = ">=0.4.0,<=0.5"
regex = "1.5"

[[bench]]
name = "bench"
harness = false

[badges]
maintenance = { status = "actively-developed" }
