[package]
name = "boostvoronoi"
version = "0.2.0"
authors = ["eadf"]
edition = "2018"
description = "Boost voronoi ported to 100% rust"
readme = "README.md"
repository = "https://github.com/eadf/boostvoronoi.rs"
license-file = "LICENSE"
keywords = ["voronoi", "sweepline", "geometry"]

[dependencies]
num = "0.3"
ordered-float = "2.0"
fnv = "1.0"
rb_tree = "0.3"
vec_map = "0.8"
num-bigint = "0.3"
num-traits = "0.2"
geo = "0.17"

[[example]]
name="piston_gui"
path= "example/piston_gui.rs"

[[example]]
name="simple"
path= "example/simple.rs"

# this bin is for development test purposes
[[bin]]
name="main"
path="src/main.rs"

[dev-dependencies]
piston = "0.52.1"
piston2d-opengl_graphics = "0.77.0"
piston2d-graphics = "0.39.0"
piston2d-touch_visualizer = "0.29.0"
pistoncore-sdl2_window="0.67.0"

